// Live call assist toolkit: one-tap AI tools that read the call so far (+ Modo's trained company knowledge).
export const TOOLS = [
  { id: "objection", label: "Handle objection", icon: "Shield", input: "Objection (blank = the latest one)", prompt: "Give the agent 2 short, honest ways to answer this objection, in natural spoken English. Use the company's approved answer if there is one. Then one question to keep the conversation going." },
  { id: "nextq", label: "Next best question", icon: "HelpCircle", prompt: "Suggest the single best next question to ask the customer right now, plus 2 backups. Short, natural, one line each." },
  { id: "close", label: "3 ways to close", icon: "Target", prompt: "Write 3 different closing lines for this moment (assumptive, choice, summary close). Honest, no pressure tactics, one or two sentences each." },
  { id: "empathy", label: "Say it with empathy", icon: "Heart", input: "What you want to say (optional)", prompt: "Give 2 warm, empathetic lines the agent can say now that acknowledge how the customer feels, then steer back to helping them." },
  { id: "explain", label: "Explain price simply", icon: "Receipt", prompt: "Explain the offer and price in plain words a customer understands in 20 seconds: what they pay now, what they'll pay, what they save, and any one-time fees. Use only numbers said on the call or in company knowledge; say what's missing if a number isn't known." },
  { id: "savings", label: "Work out savings", icon: "Calculator", input: "Bill and discount (blank = from the call)", prompt: "Work out the customer's savings: monthly, yearly, and over a 12-month contract. Show the maths in 3-4 short lines. If a number is missing, say which one to ask for." },
  { id: "summary", label: "Summary so far", icon: "FileText", prompt: "Summarise the call so far in 4 short bullet lines: who, what they want, what's been offered, where it stands." },
  { id: "followup", label: "Follow-up text & email", icon: "Send", prompt: "Write (1) a friendly SMS under 300 characters and (2) a short email with a subject line, following up on this call. Include only facts from the call. Sign as the agent." },
  { id: "compliance", label: "Compliance check", icon: "ShieldCheck", prompt: "Check the call against telemarketing and company rules: introduced self/company, said the call may be recorded, clear price, fees and contract terms, no misleading promises, consent before signing up, no pressure. List what's done ✓ and what's still missing ✗ with the exact line to say." },
  { id: "spanish", label: "Say it in Spanish", icon: "Languages", input: "What to say (blank = the suggested next line)", prompt: "Translate what the agent wants to say into natural, polite US Spanish they can read out loud, then a simple pronunciation guide." },
  { id: "translate", label: "Translate customer", icon: "Globe", input: "What the customer said (any language)", prompt: "Translate what the customer said into English, and suggest a short reply in the customer's language with an English meaning." },
  { id: "rephrase", label: "Say this better", icon: "Wand2", input: "What you want to say", prompt: "Rewrite the agent's sentence so it's clear, confident, friendly and grammatically correct. Give 2 versions: short and warm." },
  { id: "compare", label: "Why us vs. them", icon: "Scale", prompt: "Give 3 honest reasons this offer beats what the customer has now, based only on what was said and company knowledge. No invented facts about competitors; if unsure, suggest a question instead." },
  { id: "upsell", label: "Bundle & upsell ideas", icon: "Layers", prompt: "Suggest up to 3 relevant add-ons or bundles (e.g. internet + wireless, extra lines) that genuinely fit this customer, with one line to offer each. Skip it if nothing fits." },
  { id: "calm", label: "Calm an upset customer", icon: "Wind", prompt: "The customer is upset. Give a 3-step de-escalation: acknowledge, apologise/own, next step. Exact words to say, short." },
  { id: "voicemail", label: "Voicemail script", icon: "Voicemail", prompt: "Write a 20-second voicemail for this customer (or a new lead if unknown): name, company, reason, benefit, callback number placeholder [number], best time." },
  { id: "factcheck", label: "Did I say anything wrong?", icon: "SearchCheck", prompt: "Check what the AGENT said for wrong prices, promises the company doesn't make, confusing statements or grammar mistakes. Quote each problem and give the correct version. If all good, say so." },
  { id: "persona", label: "Read the customer", icon: "User", prompt: "Describe this customer's style in 2 lines (e.g. analytical, busy, price-focused, needs reassurance) and give 3 tips on how to talk to them right now." },
  { id: "callback", label: "Book a callback", icon: "CalendarClock", prompt: "Suggest the best callback plan: when (considering what the customer said and their likely time zone), what to say to book it, and a one-line note for the next call." },
  { id: "wrapup", label: "Wrap-up note", icon: "ClipboardCheck", prompt: "Write the after-call note: result (sale / callback / not interested / other), key details, what was promised, next step. 3-5 short lines, ready to paste." },
];
export const toolById = (id) => TOOLS.find((t) => t.id === id);
