// What changed in each Modo version. Shown to admin (Updates) and to everyone in "What's new".
// A note is a string (everyone) or { text, for: "admin" | "agent" }. Add an entry with every release.
export const CHANGELOG = [
  { version: "3.2.0", date: "2026-10-07", notes: [
    "Chat → #modo-training: lessons and call guides from management. Read each one, tap Mark as read, tick the checklist while you practise, and ask questions in the lesson's thread",
    "Day / Night: one tap on the sun/moon at the top. Switching is instant now (no more freeze when picking Night)",
    { text: "#modo-training: New lesson button (paste any guide; # headings, \"quotes\" for lines to say, - bullets, [ ] checklist, ! warnings), edit/delete, and see who has read each lesson and who hasn't", for: "admin" },
    { text: "Modo AI learns every #modo-training lesson, so call assist and the AI coach follow the same guide", for: "admin" },
    "#modo-training lesson: everyday American English — slang customers use, what it means and how to reply",
    "Product knowledge in #modo-training: Verizon plans (Simplicity, myPlan), Verizon Home (Fios, 5G Home, Frontier), AT&T, T-Mobile, cable/fiber/prepaid providers and a terms glossary",
    { text: "Chat → #ups-bot (admins only): send a tracking number with the order number or customer name and the Modo bot saves it on the sale and checks UPS; you can also set the step yourself (\"delivered 1Z…\"), add a return package (\"return 1Z… #12345\"), or type list for sales missing tracking", for: "admin" },
    { text: "Chat → #notepad-coach (admins only): the Modo bot posts by itself whenever an agent's notepad changes — summary plus what to say to each customer and how to engage them. Coach everyone now button too", for: "admin" },
    { text: "Team → Agent notepads → Notepad coach: Modo AI summarises every agent's notepad and tells you, per customer, what to say and how to engage them (card numbers, SSNs and PINs are hidden from the AI first)", for: "admin" },
    { text: "AI → Product knowledge: search every provider card, filter by provider, ask Modo AI, add or edit knowledge", for: "admin" },
  ] },
  { version: "3.1.0", date: "2026-10-06", notes: [
    "Sales: a small picture of each device (iPhone, iPad, Galaxy, Pixel, watch, earbuds, laptop) in its color",
    "Congrats! When admin marks your sale Active you get a phone alert and a celebration in Modo",
    "UPS tracking on every sale with a package: Track on UPS link and a live progress graphic (label → dropped off → on the way → out for delivery → delivered)",
    { text: "Chat → #sales-updates: the Modo bot posts every change to every sale (new, Active, labels, tracking, drop-off, delivered, values, deletes)", for: "admin" },
    { text: "Profile menu → Change my password (kept across updates)", for: "admin" },
    { text: "Modo bot tracks UPS packages by itself and alerts you when a status changes; connect UPS tracking (or use your Shippo token) in Connectors", for: "admin" },
  ] },
  { version: "3.0.0", date: "2026-10-06", notes: [
    "Phone: calls happen inside Modo on your VICIdial lines, you only allow the microphone; a call bar with mute, keypad and hang up follows you on every page",
    "Auto dialer: Auto-dial dials the next lead by itself after you save a result, plus a Next lead button",
    "AI assistant beside every dialer: opening lines, objection answers, what to say next, tidy my note",
    "My recent calls on the dialer pages, with Call again",
    "Home screen buttons for every page, with search and ☆ to pin favourites",
    "What's new (this page) for everyone",
    { text: "Dialer works from Vercel: Modo signs its own server in on the dialer firewall page; optional Office relay; Connection check in Dialer setup", for: "admin" },
    { text: "Recent calls on the Overview now come from Modo's own call log, so they show even when the dialer is unreachable", for: "admin" },
    { text: "Drive: private files and a daily 2 am backup stored only in your Google Drive or Dropbox", for: "admin" },
    { text: "Connected apps: one place to connect Google Drive, Dropbox, AI, dialer, labels and more; connected apps appear in the menu under Apps", for: "admin" },
    { text: "Return labels: see prices first, then Pay & create label, with a link to your Shippo payment card", for: "admin" },
  ] },
  { version: "2.9.0", date: "2026-10-06", notes: [
    { text: "Sales: each device's value today (new and used) looked up online; Active device value total", for: "admin" },
    { text: "Automatic UPS return labels through Shippo, emailed to the customer", for: "admin" },
    "New top bar: search in the bar, solid phone menu, no sideways scrolling on phones",
  ] },
  { version: "2.8.0", date: "2026-10-05", notes: ["AI Builder: describe any app, tool or page and Modo builds it live; keep chatting to change it"] },
  { version: "2.7.0", date: "2026-09-26", notes: ["Modo for Windows: a real desktop app (own icon and window, no browser bar, starts with the PC)", "Optional kiosk mode locks a company PC to Modo only (Task Manager, Control Panel, Run, USB blocked); admin PIN to exit", "Admin → Tools → Windows app: download the installer and set what it does on each PC", "Early shift end with admin approval + one-time code; 20-tool AI toolkit in Call assist"] },
  { version: "2.6.0", date: "2026-09-26", notes: ["Dialer setup page: pick VICIdial or any other dialer, link agents, edit results and pause codes", "Train Modo AI: company knowledge used by every AI feature + training-data export", "Live assist: objections with answers, customer questions, key facts, call checklist, buying signals", "Listen to all agents at once with live spectrum and captions", "Discount calculator: Wireless (lines × price) and Internet & Wireless bundle", "Updates page"] },
  { version: "2.5.0", date: "2026-09-26", notes: ["Modo dialer for agents (VICIdial in the background)", "More lookups: city ZIPs, weather, distance, US holidays; lookup API presets", "Notepad search and Lookups layout fixes"] },
  { version: "2.4.0", date: "2026-09-26", notes: ["Budget Ease section with encrypted SSN last 4 and date of birth", "AI buttons across Modo", "Day mode button fixes"] },
];
